name: Deploy to Netlify

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare - Checkout
        uses: actions/checkout@v4

      - name: Prepare - Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Prepare - Install dependencies
        run: npm ci

      - name: Prepare - Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: .

  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Build - Download source
        uses: actions/download-artifact@v4
        with:
          name: source

      - name: Build - Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Build - Install dependencies
        run: npm ci

      - name: Build - Vite
        run: npm run build

      - name: Build - Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy - Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Deploy - Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Deploy - Netlify
        run: netlify deploy --dir=dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
